name: Markdown to PDF

on:
  push:
    branches:
      - main   # Ejecutar automáticamente cuando se hace push a main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde Actions

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Convertir Markdown a PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./                 # Carpeta con los archivos Markdown
          output_dir: pdfs               # Carpeta donde guardará los PDFs

      - name: Subir PDFs generados
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs  # Subir los PDFs generados como un archivo comprimido
